services:
  - type: web
    name: ia06-backend
    env: node
    region: oregon
    rootDir: src/backend
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    autoDeploy: true
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB_NAME
        value: ia06
      - key: PORT
        value: 3000
